import * as yup from 'yup'

export const schema = yup.object().shape({
    profession: yup.string().required('Profession is required'),
    sourceOfIncome: yup.string().required('Source of Income is required'),
    purposeOfLoan: yup.string().required('Purpose of Loan is required'),
    repeatCustomer: yup.string().required('Repeat Customer status is required'),
    bnsName: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Business Name is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    natureOfBns: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Nature of Business is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    bnsAddress: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Business Address is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    phoneNo: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Phone Number is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    description: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Description is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    prevExpInBns: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Previous Experience in Business is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    ownOfBnsPlace: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Ownership of Business Place is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    costOfBns: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Cost of Business is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    bnsRatings: yup.string().when('sourceOfIncome', {
        is: 'Business Income',
        then: (schema) => schema.required('Business Ratings is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    borrowerDistrict: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Borrower District is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    sowodo: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Sowodo is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    loanTenure: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Loan Tenure is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    insCompany: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Insurance Company is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    policyIssuedDate: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Policy Issued Date is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    policyExpiredDate: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Policy Expired Date is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    receiptNo: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Receipt Number is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    premiumRate: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Premium Rate is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    animalOrCrop: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Animal or Crop is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    buffaloes: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Number of Buffaloes is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    cows: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Number of Cows is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    bulls: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Number of Bulls is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    collateral: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Collateral is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    claimLodged: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Claim Lodged is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    animalTagging: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Animal Tagging is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    natureOfTheBorrower: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Nature of the Borrower is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    ownOfLand: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Ownership of Land is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    floodsFactor: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Floods Factor is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    irrigation: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Irrigation is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    methods: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Methods is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    proofOfCult: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Proof of Cultivation is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    expInCult: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Experience in Cultivation is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    agriSecured: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Agricultural Secured is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    marketCheck: yup.string().when('sourceOfIncome', {
        is: 'Agricultural Income',
        then: (schema) => schema.required('Market Check is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    employer: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Employer is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    typeOfBusiness: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Type of Business is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    designation: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Designation is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    currEmpPeriod: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Current Employment Period is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    empAddress: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Employment Address is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    typeOfJob: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Type of Job is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    natureOfEmp: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Nature of Employment is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    contactNo: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Contact Number is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    residenceOrWorking: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Residence or Working Place is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
    proofOfSalary: yup.string().when('sourceOfIncome', {
        is: 'Salary Income',
        then: (schema) => schema.required('Proof of Salary is required'),
        otherwise: (schema) => schema.notRequired(),
    }),
})

// "profession": "Salaried",
// "sourceOfIncome": "Salary income",
// "purposeOfLoan": "5",
// "employer": "Salary income",
// "typeOfBusiness": "typeOfBusiness",
// "designation": "designation",
// "currEmpPeriod": "12y",
// "empAddress": "245,Rajagiriya",
// "typeOfJob": "Privatee",
// "natureOfEmp": "Permanet",
// "contactNo": "0715756956",
// "residenceOrWorking":"Residence or working place of applicant",
// "proofOfSalary":"3 months bank statement provided",
// "repeatCustomer":"New customer/Average 15 days delay"

// "appraisalId": "AP000000000001",
// "idx": "LSTK0000000002341",
// "profession": "Salaried",
// "sourceOfIncome": "Salary income",
// "borrowerDistrict": "s",
// "sowodo": "ss",
// "loanTenure": "s",
// "insCompany": "s",
// "policyIssuedDate": "2022-01-01T00:00:00.000+00:00",
// "policyExpiredDate": "2022-01-01T00:00:00.000+00:00",
// "receiptNo": "s",
// "premiumRate": "s",
// "animalOrCrop": "s",
// "buffaloes": "s",
// "cows": "s",
// "bulls": "s",
// "collateral": "s",
// "claimLodged": "s",
// "animalTagging": "s",
// "purposeOfLoan": "s",
// "natureOfTheBorrower": "s",
// "ownOfLand": "",
// "floodsFactor": "",
// "irrigation": "",
// "methods": "",
// "proofOfCult": "",
// "expInCult": "",
// "agriSecured": "",
// "marketCheck": "Mssss",
// "status": "A"

// { label: 'Salary Income', value: 'Salary Income' },
// { label: 'Rental Income', value: 'Rental Income' },
// { label: 'Business Income', value: 'Business Income' },
// { label: 'Agricultural Income', value: 'Agricultural Income' },
// { label: 'Live Stock Income', value: 'Live Stock Income' }